### ISSUE TITLE
Déploiement SaaS [ROI: 313]

### ISSUE THREAD

**Issue by jbcrestot** [ScrumBoard-it/ScrumBoard-it#26]
[BV: 25]
[CT: 8]

ETQ utilisateur
J'AIMERAI pouvoir me connecter à un service depuis n'importe où
AFIN DE ne pas avoir a gérer une installation locale

[CA]
Je dois pouvoir me connecter depuis n'importe quel poste interne à l'application via une page web

**Comment by brieucpouliquen** [comment]
- Déployer

**Comment by brieucpouliquen** [comment]
Pour un déploiement en prod :
- Serveur connecté à internet et référencé (dans le domaine Canaltp par exemple)
- Connexion SSH disponible sur le serveur
- PHP 5.5.9 minimum en fonction sur le serveur (dans l'idéal, la même version PHP que sur le serveur de développement)

**Comment by brieucpouliquen** [comment]
Deployed.
