### ISSUE TITLE
Template d'impression

### ISSUE THREAD

**Issue by jbcrestot** [ScrumBoard-it/ScrumBoard-it#27]
[BV: 20][CT: 8][ROI: 250]

ETQ utilisateur
JS avoir le choix de la disposition des éléments de mes post-its
AD avoir des post-its qui sont plus clairs

**Comment by alcalyn** [comment]
ETQ user
Je souhaite pouvoir imprimer un template depuis scrummboardit avec les emplacements des postit, le sens de collage des posit (ou mettre la bande collante), le sens d'impression (haut/bas)
Afin de facilment coller mes postit et ne pas imprimer à l'enver

**Comment by jbcrestot** [comment]
Cette US pourrait répondre au besoin #39

**Comment by brieucpouliquen** [comment]
#65
