### ISSUE TITLE
impressions identiques sur tous les navigateurs

### ISSUE THREAD

**Issue by jbcrestot** [ScrumBoard-it/ScrumBoard-it#31]
[BV: 5]
[CT: ]

ETQ utilisateur
J'AIMERAI pouvoir imprimer mes post-it de la même façon depuis tous les navigateurs
AFIN DE gagner du temps

**Comment by ooga** [comment]
https://codereview.chromium.org/1817873002

À checker !

**Comment by ooga** [comment]
Resolved in Chrome
