### ISSUE TITLE
Intégration github issues

### ISSUE THREAD

**Issue by jbcrestot** [ScrumBoard-it/ScrumBoard-it#32]
[BV: 60]
[CT: 21]

ETQ utilisateur
J'AIMERAI pouvoir imprimer des "issues" github
AFIN DE de pouvoir utiliser scrumboard-it avec mon projet github

---
### Critères d'acceptance
Connexion avec un compte github en plus d'un compte jira
Pouvoir visualiser les issues des différents dépôts sur la page principales
Pouvoir filtrer les issues d'un dépôt en fonction d'un ou plusieurs label(s), d'un millestone et/ou d'un état (open/close)

**Comment by brieucpouliquen** [comment]
Not finished during the sprint 2.

**Comment by brieucpouliquen** [comment]
Problems : 
- Number of repos can be very important => difficulties to paginate correctly.
- In case of non-admin role in a repo, cannot write labels => Problem the "Printed" label

Possible solution : uses of a database.
Advantages :
- Will resolve the problem of the print property
- Reduces callings to the API's => velocity ?

Inconvenients :
- The database has to be maintained

**Comment by jbcrestot** [comment]
#51
