### ISSUE TITLE
Serveur de développement

### ISSUE THREAD

**Issue by brieucpouliquen** [ScrumBoard-it/ScrumBoard-it#34]
ETQ développeur
J'AIMERAIS un accès avec droits administrateur à un serveur de développement interne à l'entreprise
AFIN DE déployer l'application dans le but de la tester en réseau et la rendre disponible aux employés sur le réseau

**Comment by ooga** [comment]
on peut utiliser le serveur de Dev
Créer un user et mettre des ACL sur un dossier pour le deploiement

**Comment by brieucpouliquen** [comment]
- Port SSH (22) ouvert
- Si possible avec Apache2 pré-installé

**Comment by jbcrestot** [comment]
c'est fait, tu as donc tout ce qu'il te faut pour déployer sur le serveur de dev?

**Comment by brieucpouliquen** [comment]
Je vois ça demain merci 😉

**Comment by brieucpouliquen** [comment]
- PHP 5.5 required to run Symfony 3. Incompatible with the present server.

**Comment by jbcrestot** [comment]
http://jira.canaltp.fr/browse/DEVOP-344

**Comment by jbcrestot** [comment]
Le server est pret, tu peux venir me voir pour les accès
